### ISSUE TITLE
[swscaler @ 0x55a0143f0fc0] deprecated pixel format used, make sure you did set range correctly

### ISSUE THREAD

**Issue by gidTT** [phillipberndt/pqiv#266]
i get error

[swscaler @ 0x55a0143f0fc0] deprecated pixel format used, make sure you did set range correctly

in an endless row when trying to view live photos made on iphone and pqiv doesn't react on any command, not even 'q'

$ pqiv *.MOV

while
$ pqiv *.HEIC
works well.

(running under arch linux)

**Comment by phillipberndt** [comment]
Thanks. Can you take a demo live picture and share that here?

**Comment by gidTT** [comment]
here click on download. it is original file. [https://photos.app.goo.gl/XpXM18T363e1ZtYHA](url)

it's pqiv 2.13.2 from arch linux repo

**Comment by phillipberndt** [comment]
I think that the commit I just pushed addresses this.

**Comment by gidTT** [comment]
updated these packages with pacman from repo: pqiv-2.13.3-1 and ffmpeg-2:8.0.1-1

$ pqiv -t --command-1="gio trash" *.MOV

but the previously reported error persists.
I just did a complete arch linux update and the error still persists after reboot.

I see the latest version is now pqiv-2.13.3. i installed it from code.
and get these errors:

Didn't recognize file `IMG_6498.MOV': Both its extension and MIME-type `video/quicktime' are unknown. Fall-back to default file handler.

[... same for all other MOV files in the directory]

Failed to load image IMG_6498.MOV: Unrecognised image file format

[... same for all other MOV files in the directory]

No images left to display.

(pqiv:4399): GLib-CRITICAL **: 20:39:35.795: g_thread_join: assertion 'thread' failed

p.s.: i use MATE desktop

**Comment by phillipberndt** [comment]
The fix is only in the development version, if you build from git master.

You'll need to install all build time dependencies for pqiv to build it. It automatically skips libav / ffmpeg support if the development package for that is missing.

**Comment by gidTT** [comment]
you mean i need to install libav / ffmpeg development packages and then build your latest commit pqiv-2.13.3 again?

**Comment by phillipberndt** [comment]
Yup. The latest commit isn't released as a version yet, so do a git clone & build from that.

**Comment by gidTT** [comment]
these?

$ yay ffmpeg-git
..
aur/ffmpeg-git 8.1.r121357.g7896cc67c1-1 (+74 0.14) 
    Complete solution to record, convert and stream audio and video (git version)

$ yay libav-git
aur/gst-libav-git 1.24.0.r37.g95bafc4934-1 (+21 0.00) 
    GStreamer Multimedia Framework (Git version) - libav plugin

**Comment by NHOrus** [comment]
https://unix.stackexchange.com/questions/28972/why-are-there-no-dev-packages-in-arch-linux
If you have header files in output of `/usr/include/libav*` and pc files in output of `ls /usr/lib/pkgconfig/libav*`, you must be good to go.

And for cloning, you need to clone this, `pqiv` repo, not aur packages for ffmpeg or libav. And build `pqiv` according to [README](https://github.com/phillipberndt/pqiv#installation). You may want to set PREFIX to something like ~/.local for make install.
