### ISSUE TITLE
Problems with viewing images in archives

### ISSUE THREAD

**Issue by noctuid** [phillipberndt/pqiv#70]
I think it would be nice if pqiv could open archives regardless of the actual extension name. Often I'll have an image gallery or something in a zip file, but pqiv will only open it if I change the extension. 

If possible, it would also be nice if pqiv could work fine even if there is, for example, a text file in a zip as well. Images will start vanishing for me in such archives until there is only one left. This also happens for some archives that are only jpgs or pngs. If I add a text file to an archive that works correctly normally, it seems to always cause this to happen. It seems that sometimes images can be out of order as well.

I just tried this with [an igmur gallery](https://imgur.com/gallery/hOF1g) of only jpgs and both these issues (out of order and vanishing) happen for me. Images seem to disappear mainly when going to the previous image. Once I get from the last image to the first image, they start quickly disappearing when going forward too.

**Comment by phillipberndt** [comment]
The file extension restriction is because of #61. Once that issue is resolved, I'll remove the restriction as well.

I can reproduce the vanishing files issue. Thanks for reporting that, I'll fix it asap.

**Comment by phillipberndt** [comment]
The problem with the vanishing files should be resolved now. For support of other archive types, see #61.

**Comment by noctuid** [comment]
Thanks. The vanishing issue definitely seems to be fixed. However, the images are still not sorted in the same way that they would be if I extracted the archive. Looking at the image title in the info box excluding the identical prefixes, the first image is "127...", the second is "001...", the third is "049...", etc. Can you replicate this?

**Comment by phillipberndt** [comment]
Try using the -n option to pqiv!

Fox Kiester <notifications@github.com> schrieb am Fr., 16. Dez. 2016, 18:52:

**Comment by noctuid** [comment]
Thanks that makes sense. I'm used to not having to sort, so I didn't even think about it. Thanks.

**Comment by phillipberndt** [comment]
I went ahead and did a first implementation in 5c109db / #61. I'd appreciate your opinion :-)
