### ISSUE TITLE
Fullscreen mode with transparent background

### ISSUE THREAD

**Issue by pa-d-v** [phillipberndt/pqiv#90]
Thanks for the fantastic pqiv, I'm using version 2.8.5
In window mode images are automatically scaled down to about 80% of screen resolution. It would be nice if there was a scale down option to use 100% of screen to get full height or full width image like in full screen mode (original qiv has --scale_down option that does this). Zoom level is relative to the original resolution of the image and can't be used for this since portrait and landscape images and different image resolutions would need different zoom levels each time to achieve full screen height or full screen width images in window mode.
An easier way would be to see it as fullscreen mode with transparent background showing other windows underneath but currently --transparent-background option does nothing in --fullscreen mode since we always get a black background.

Regards,
Pascal

**Comment by phillipberndt** [comment]
`--transparent-background` should make the background in fullscreen mode transparent (..and it does here). Please give me a few details on your setup, I'll try to reproduce the issue.

As for your request, please have a look at the `configurable-scale-up` branch I just created. Is this what you've had in mind?

**Comment by pa-d-v** [comment]
I'm using i3 tiling window manager with --transparent-background in fullscreen mode it show the desktop
background transparent but no other windows underneath when compositing manager (dunst) is enabled. But this is indeed probably an issue with i3 since with mutter used in gnome that seems to work. In window mode it show windows underneath.

I tested the branch with --scale-mode-screen-fraction=1.0 thanks for adding this. There seems to be a difference between portrait and landscape images, landscape images sometimes don't span the whole screen height missing a few pixels while portrait do or the other way around. The info box image scale % seems to always indicate a whole number ending in .00 (e.g. 45.00% or 25.00%) so probably caused by a rounding issue? Why are 2 digits behind the decimal point shown? I would expect it to use the same full height for portrait or landscape images.

**Comment by pa-d-v** [comment]
The default automatic scaledown seems to scale up images that fit the screen with --scale-mode-screen-fraction=1.0 e.g. 1024 height while my screen is 1080 height shows 105.00% in the info box and sometimes a black border around the image best seen in window mode. I would expect the default scaling only to scale down.

**Comment by phillipberndt** [comment]
My bad, I forgot to replace the hardcoded 80% with the option in once place. Should be fixed now!

**Comment by pa-d-v** [comment]
Looks ok now for images that fit the screen (black border and 105.00% are gone), thanks for the fix.
The few pixels difference between portrait and landscape images is still there, this is caused by a rounding issue since in fullscreen mode info box image scale % shows 2 digits behind the decimal point while in windows mode it always ends in .00
Also a dashed line at the bottom or the right of the image can sometimes be seen in window mode because of the checkboard pattern behind it probably also because of the rounding. Can the rounding be fixed?

**Comment by pa-d-v** [comment]
I still see black left and right borders with mutter used in gnome in window mode for images that don't fit the screen but in i3 not. Dashes lines can be notice here as well.

**Comment by phillipberndt** [comment]
>  Also a dashed line at the bottom or the right of the image can sometimes be seen in window mode because of the checkboard pattern behind it probably also because of the rounding. Can the rounding be fixed?

I just merged this branch to master, where that issue is already fixed.

> I still see black left and right borders with mutter used in gnome in window mode for images that don't fit the screen but in i3 not.

Do you maybe have a task bar or something that prevents the window from actually resizing to 100% height? That would explain the black borders: pqiv asks for WxH px size, the WM makes it Wx(H-something) such that the window does no langer have the correct aspect ratio, pqiv notices and draws black borders around the image. Try using `--enforce-window-aspect-ratio`.

(The automatic scale factor is always rounded down towards a full percentage btw, search for

    current_scale_level = round(current_scale_level * 100.) / 100.;

in the source code and remove it if you'd like, I doubt that it'll resolve your issue though. The info box shows two decimal digits because you can still manually zoom to arbitrary zoom levels.)

**Comment by pa-d-v** [comment]
Thanks for including --scale-mode-screen-fraction in master and fixing the dashed lines.
I have removed current_scale_level = round(current_scale_level * 100.) / 100.; since I'm always using --scale-mode-screen-fraction=1 in 2 places and the full screen height for portrait and landscape image is used now, thanks for pointing that out.
Since I'm trying to achieve fullscreen images so I can still see other windows underneath using i3 wm I need to use window mode (since --transparant-background doesn't work) it would be nice if --scale-mode-screen-fraction >= 1.0 would actually use the full screen height and do no rounding.

**Comment by phillipberndt** [comment]
I removed the line from master. It's purely cosmetic, after all, and breaks your use case.
